// สร้างอัตโนมัติโดย scripts/gen-arch.mjs ตอน build — **ห้ามแก้ด้วยมือ**
// แก้ที่นี่จะถูกเขียนทับรอบหน้า และทำให้ผังในหน้า /core/arch โกหกจนกว่าจะมีคนสังเกต
export const ARCH_ADMIN = {
  "generatedAt": "2026-10-01T15:16:31.291Z",
  "site": "admin.gucut.com",
  "project": "gucut-admin",
  "repo": "gucut-next",
  "apiRoutes": {
    "count": 51,
    "names": [
      "ads",
      "ai-visibility",
      "auth/login",
      "auth/whoami",
      "bills",
      "bills/download",
      "bills/drivesync",
      "bills/dupcheck",
      "bills/fetchzip",
      "bills/file",
      "bills/fixmonth",
      "bills/report",
      "bills/status",
      "bills/upload",
      "bills/vendor",
      "bills/watch",
      "bills/zip",
      "build",
      "build-time",
      "catalog/state",
      "connections",
      "export-log",
      "glasses-log",
      "google/auth",
      "google/callback",
      "import",
      "ipcheck",
      "mailcheck",
      "netlify-credits",
      "reorder",
      "returns",
      "returns-summary",
      "returns/received",
      "rokid/v1/chat/completions",
      "rokid/v1/models",
      "sales-report",
      "sheets",
      "shopify/install",
      "shopify/oauth-callback",
      "staff-users",
      "store/products",
      "telegram/set-webhook",
      "telegram/webhook",
      "tracker",
      "tracker/image/[key]",
      "tracker/migrate",
      "tracker/upload",
      "transfer",
      "web/[...path]",
      "webfile/[name]",
      "zort"
    ]
  },
  "pages": {
    "count": 125,
    "core": 88,
    "coreNames": [
      "/core",
      "/core/accounting-docs",
      "/core/admin-log",
      "/core/arch",
      "/core/backup",
      "/core/branches",
      "/core/branches/new",
      "/core/bundles",
      "/core/bundles/[sku]",
      "/core/bundles/new",
      "/core/buy-report",
      "/core/categories",
      "/core/categories/detail",
      "/core/channels",
      "/core/chat",
      "/core/coverage",
      "/core/customer-report",
      "/core/customers",
      "/core/customers/detail",
      "/core/customers/new",
      "/core/factory-orders",
      "/core/feed-health",
      "/core/finance",
      "/core/glasses-log",
      "/core/import",
      "/core/leadtime",
      "/core/logistics",
      "/core/manual",
      "/core/marketplace",
      "/core/marketplace-products",
      "/core/missing-sku",
      "/core/mkp-finance",
      "/core/money-transfers",
      "/core/moves",
      "/core/other-expense",
      "/core/other-income",
      "/core/packing",
      "/core/packing/pack",
      "/core/peak",
      "/core/pos",
      "/core/purchases",
      "/core/purchases/detail",
      "/core/purchases/new",
      "/core/purchases/returns",
      "/core/purchases/returns/new",
      "/core/quotations",
      "/core/quotations/detail",
      "/core/quotations/new",
      "/core/receive",
      "/core/registry",
      "/core/reorder",
      "/core/reports",
      "/core/return-orders",
      "/core/return-orders/detail",
      "/core/salepages",
      "/core/sales",
      "/core/sales/detail",
      "/core/sales/new",
      "/core/sales/print",
      "/core/setting-notify",
      "/core/setting-sms",
      "/core/setting-tracking",
      "/core/settings-company",
      "/core/settings-jobs",
      "/core/settings-profile",
      "/core/settings-roles",
      "/core/settings-users",
      "/core/settings-users/add",
      "/core/soon/[key]",
      "/core/stock",
      "/core/stock-push",
      "/core/stock-stuck",
      "/core/stock/[sku]",
      "/core/stock/[sku]/edit",
      "/core/stock/cost",
      "/core/stock/new",
      "/core/stock/no-image",
      "/core/stock/print",
      "/core/transfers",
      "/core/transfers/detail",
      "/core/usage",
      "/core/variants",
      "/core/wallet",
      "/core/zort-arch",
      "/core/zort-archive",
      "/core/zort-claims",
      "/core/zort-noapi",
      "/core/zort-webhook"
    ],
    "names": [
      "/",
      "/ads",
      "/ai-visibility",
      "/bills",
      "/core",
      "/core/accounting-docs",
      "/core/admin-log",
      "/core/arch",
      "/core/backup",
      "/core/branches",
      "/core/branches/new",
      "/core/bundles",
      "/core/bundles/new",
      "/core/buy-report",
      "/core/categories",
      "/core/categories/detail",
      "/core/channels",
      "/core/chat",
      "/core/coverage",
      "/core/customer-report",
      "/core/customers",
      "/core/customers/detail",
      "/core/customers/new",
      "/core/factory-orders",
      "/core/feed-health",
      "/core/finance",
      "/core/glasses-log",
      "/core/import",
      "/core/leadtime",
      "/core/logistics",
      "/core/manual",
      "/core/marketplace",
      "/core/marketplace-products",
      "/core/missing-sku",
      "/core/mkp-finance",
      "/core/money-transfers",
      "/core/moves",
      "/core/other-expense",
      "/core/other-income",
      "/core/packing",
      "/core/packing/pack",
      "/core/peak",
      "/core/pos",
      "/core/purchases",
      "/core/purchases/detail",
      "/core/purchases/new",
      "/core/purchases/returns",
      "/core/purchases/returns/new",
      "/core/quotations",
      "/core/quotations/detail",
      "/core/quotations/new",
      "/core/receive",
      "/core/registry",
      "/core/reorder",
      "/core/reports",
      "/core/return-orders",
      "/core/return-orders/detail",
      "/core/salepages",
      "/core/sales",
      "/core/sales/detail",
      "/core/sales/new",
      "/core/sales/print",
      "/core/setting-notify",
      "/core/setting-sms",
      "/core/setting-tracking",
      "/core/settings-company",
      "/core/settings-jobs",
      "/core/settings-profile",
      "/core/settings-roles",
      "/core/settings-users",
      "/core/settings-users/add",
      "/core/stock",
      "/core/stock-push",
      "/core/stock-stuck",
      "/core/stock/cost",
      "/core/stock/new",
      "/core/stock/no-image",
      "/core/stock/print",
      "/core/transfers",
      "/core/transfers/detail",
      "/core/usage",
      "/core/variants",
      "/core/wallet",
      "/core/zort-arch",
      "/core/zort-archive",
      "/core/zort-claims",
      "/core/zort-noapi",
      "/core/zort-webhook",
      "/factory",
      "/import",
      "/login",
      "/orders",
      "/products",
      "/returns",
      "/returns/inbox",
      "/returns/receive",
      "/sales",
      "/settings/connections",
      "/settings/connections/health",
      "/site",
      "/site/attendance",
      "/store/products",
      "/tracker",
      "/web/ads",
      "/web/chat",
      "/web/clip-shop",
      "/web/clips",
      "/web/comments",
      "/web/coupons",
      "/web/legacy",
      "/web/live",
      "/web/marketing",
      "/web/orders",
      "/web/payroll",
      "/web/permits",
      "/web/points",
      "/web/seo",
      "/web/status",
      "/web/videos"
    ]
  },
  "blobs": [
    "reorder",
    "returns",
    "tracker",
    "tracker-images"
  ],
  "pipe": {
    "allow": [
      "ad-stats",
      "ai-bots",
      "bot-rules",
      "chat",
      "clip-shop",
      "clip-stats",
      "core",
      "coupon",
      "feed-health",
      "legacy",
      "live",
      "marketing",
      "netlify-credits",
      "office",
      "orders",
      "payroll",
      "permit-doc",
      "points",
      "read-id",
      "reviews-ingest",
      "seo-audit",
      "shopee",
      "social",
      "status",
      "time",
      "video-pick",
      "zort-archive"
    ],
    "count": 27
  },
  "realSend": {
    "screens": [
      {
        "path": "/core/branches/new",
        "key": "branches/new",
        "open": false,
        "openFrom": "ทะเบียน"
      },
      {
        "path": "/core/bundles/new",
        "key": "bundles/new",
        "open": false,
        "openFrom": "ทะเบียน"
      },
      {
        "path": "/core/customers/new",
        "key": "customers/new",
        "open": false,
        "openFrom": "ทะเบียน"
      },
      {
        "path": "/core/import",
        "key": "import",
        "open": false,
        "openFrom": "ทะเบียน"
      },
      {
        "path": "/core/purchases/detail",
        "key": "purchases/detail",
        "open": false,
        "openFrom": "ทะเบียน"
      },
      {
        "path": "/core/purchases/new",
        "key": "purchases/new",
        "open": true,
        "openFrom": "ทะเบียน"
      },
      {
        "path": "/core/purchases/returns/new",
        "key": "purchases/returns/new",
        "open": false,
        "openFrom": "ทะเบียน"
      },
      {
        "path": "/core/quotations/new",
        "key": "quotations/new",
        "open": true,
        "openFrom": "ทะเบียน"
      },
      {
        "path": "/core/sales/new",
        "key": "sales/new",
        "open": true,
        "openFrom": "ทะเบียน"
      },
      {
        "path": "/core/stock/[sku]/edit",
        "key": "stock/[sku]/edit",
        "open": false,
        "openFrom": "ทะเบียน"
      },
      {
        "path": "/core/stock/cost",
        "key": "stock/cost",
        "open": false,
        "openFrom": "ทะเบียน"
      },
      {
        "path": "/core/stock/new",
        "key": "stock/new",
        "open": true,
        "openFrom": "ทะเบียน"
      }
    ],
    "open": 4,
    "closed": 8,
    "จอที่ประกาศ": 12,
    "ทะเบียนเปิด": 4,
    "คีย์ที่ทะเบียนเปิด": [
      "purchases/new",
      "quotations/new",
      "sales/new",
      "stock/new"
    ],
    "คีย์ที่จอขอ": [
      "branches/new",
      "bundles/new",
      "customers/new",
      "import",
      "purchases/detail",
      "purchases/new",
      "purchases/returns/new",
      "quotations/new",
      "sales/new",
      "stock/[sku]/edit",
      "stock/cost",
      "stock/new"
    ]
  },
  "integrations": [
    {
      "id": "zort1",
      "name": "ZORT ร้านหลัก",
      "what": "ออเดอร์ · สต็อก · สินค้า",
      "envs": [
        "ZORT_STORENAME_1",
        "ZORT_APIKEY_1"
      ],
      "inCode": true
    },
    {
      "id": "zort2",
      "name": "ZORT ร้านสาขา",
      "what": "บัญชีที่สอง (ceojet)",
      "envs": [
        "ZORT_STORENAME_2",
        "ZORT_APIKEY_2"
      ],
      "inCode": true
    },
    {
      "id": "pipe",
      "name": "ท่อกลางไปหน้าร้าน",
      "what": "เรียก gucut.com/api/* ด้วยรหัสของตัวเอง",
      "envs": [
        "GUCUT_WEB_ADMIN_KEY",
        "GUCUT_SITE_URL"
      ],
      "inCode": true
    },
    {
      "id": "telegram",
      "name": "Telegram",
      "what": "แจ้งเตือน + รับปุ่มอนุมัติ (webhook)",
      "envs": [
        "TELEGRAM_BOT_TOKEN",
        "TELEGRAM_CHAT_ID"
      ],
      "inCode": true
    },
    {
      "id": "google",
      "name": "Google (Gmail/ไดรฟ์)",
      "what": "เช็คเมลอนุมัติจากมาร์เก็ตเพลส",
      "envs": [
        "GOOGLE_CLIENT_ID",
        "GOOGLE_CLIENT_SECRET"
      ],
      "inCode": true
    },
    {
      "id": "ai",
      "name": "ผู้ช่วย AI",
      "what": "งานอ่าน/สรุปในหลังร้าน",
      "envs": [
        "ANTHROPIC_API_KEY",
        "GEMINI_API_KEY"
      ],
      "inCode": true
    },
    {
      "id": "rokid",
      "name": "สะพานแว่น Rokid",
      "what": "ต่อแว่นเข้ากับหลังร้าน",
      "envs": [
        "ROKID_BRIDGE_KEY"
      ],
      "inCode": true
    },
    {
      "id": "shopify",
      "name": "Shopify (ของเก่า)",
      "what": "เหลือค้างจากตอนยังใช้ Shopify",
      "envs": [
        "SHOPIFY_ADMIN_TOKEN",
        "SHOPIFY_STORE_DOMAIN"
      ],
      "inCode": true
    }
  ],
  "unlabelled": [
    "BUILD_AT",
    "BUILD_BRANCH",
    "BUILD_COMMIT",
    "BUILD_CONTEXT",
    "COMMIT_REF",
    "NETLIFY",
    "STAFF_USERS_LOCAL_DIR"
  ]
} as const;
